services:

  _defaults:
    autowire: true
    autoconfigure: true

  paloma:
    class: Paloma\Shop\Paloma

  paloma_shop.catalog:
    class: Paloma\Shop\Catalog\Catalog

  paloma_shop.checkout:
    class: Paloma\Shop\Checkout\Checkout

  paloma_shop.customers:
    class: Paloma\Shop\Customers\Customers

  paloma_shop.client_factory:
    class: Paloma\ShopBundle\SymfonyPalomaClientFactory
    arguments:
      - '@paloma_shop.channel_resolver'
      - '@paloma_shop.config'
      - '@session'
      - [] # injected by bundle extension
      - '@?paloma_shop.paloma_profiler'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 15 } # before symfony security listeners

  paloma_shop.client:
    class: Paloma\Shop\PalomaClient
    factory: 'paloma_shop.client_factory:create'

  paloma_shop.config:
    class: Paloma\ShopBundle\PalomaConfig
    arguments:
      - ~ # injected by bundle extension
      - '@router'

  paloma_shop.channel_resolver:
    class: Paloma\ShopBundle\DefaultChannelResolver
    arguments:
      - ~ # injected by bundle extension

  paloma_shop.security:
    class: Paloma\ShopBundle\Security\PalomaSecurity
    arguments:
      - '@security.token_storage'
      - '@paloma_shop.client'

  paloma_shop.security.user_provider:
    class: Paloma\ShopBundle\Security\PalomaUserProvider

  paloma_shop.security.authenticator:
    class: Paloma\ShopBundle\Security\PalomaAuthenticator

  paloma_shop.security.authentication_listener:
    class: Paloma\ShopBundle\Security\PalomaAuthenticationListener

  paloma_shop.security.logout_success_handler:
    class: Paloma\ShopBundle\Security\PalomaLogoutSuccessHandler

  paloma_shop.serializer:
    class: Paloma\ShopBundle\Serializer\PalomaSerializer

  paloma_shop.exception_listener:
    class: Paloma\ShopBundle\EventListener\PalomaExceptionListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  paloma_shop.twig_extension:
    class: Paloma\ShopBundle\Twig\PalomaTwigExtension
    tags:
      - { name: twig.extension }

  paloma_shop.twig_helper:
    class: Paloma\ShopBundle\Twig\PalomaTwigHelper
    arguments:
      - '@request_stack'
      - [] # injected by bundle extension

  # Aliases

  Paloma\Shop\Paloma:
    alias: paloma

  Paloma\Shop\Catalog\CatalogInterface:
    alias: paloma_shop.catalog

  Paloma\Shop\Checkout\CheckoutInterface:
    alias: paloma_shop.checkout

  Paloma\Shop\Customers\CustomersInterface:
    alias: paloma_shop.customers

  Paloma\Shop\PalomaClientInterface:
    alias: paloma_shop.client

  Paloma\Shop\Catalog\CatalogClientInterface:
    alias: paloma_shop.client.catalog

  Paloma\Shop\Checkout\CheckoutClientInterface:
    alias: paloma_shop.client.checkout

  Paloma\Shop\Customers\CustomersClientInterface:
    alias: paloma_shop.client.customers

  Paloma\Shop\Security\PalomaSecurityInterface:
    alias: paloma_shop.security

  Paloma\Shop\PalomaConfigInterface:
    alias: paloma_shop.config

  Paloma\ShopBundle\Serializer\PalomaSerializer:
    alias: paloma_shop.serializer