paloma_catalog:
  resource: '@PalomaShopBundle/Resources/config/routes/catalog.yaml'

paloma_content:
  resource: '@PalomaShopBundle/Resources/config/routes/content.yaml'

paloma_checkout:
  resource: '@PalomaShopBundle/Resources/config/routes/checkout.yaml'
  prefix: /checkout

paloma_customer:
  resource: '@PalomaShopBundle/Resources/config/routes/customer.yaml'
  prefix: /customer

paloma_security:
  resource: '@PalomaShopBundle/Resources/config/routes/security.yaml'
  prefix: /security

paloma_api:
  resource: '@PalomaShopBundle/Resources/config/routes/api.yaml'
  prefix: /api
