paloma_catalog:
  resource: '@PalomaShopBundle/Resources/config/routes/catalog.yaml'

paloma_checkout:
  resource: '@PalomaShopBundle/Resources/config/routes/checkout.yaml'
  prefix: /checkout

paloma_security:
  resource: '@PalomaShopBundle/Resources/config/routes/security.yaml'
  prefix: /security

paloma_api:
  resource: '@PalomaShopBundle/Resources/config/routes/api.yaml'
  prefix: /api

#paloma_checkout:
#  resource: '@PalomaShopBundle/Resources/config/routes/checkout.yaml'
#  prefix: /checkout
#
#paloma_account:
#  resource: '@PalomaShopBundle/Resources/config/routes/account.yaml'
#  prefix: /account
