paloma_catalog_home:
  path: /
  controller: paloma_shop.controller.catalog_home::view
  methods: GET

paloma_catalog_search:
  path: /search
  controller: paloma_shop.controller.catalog_search::view
  methods: [ GET, POST ]

paloma_catalog_category:
  path: /c/todo
  controller: paloma_shop.controller.catalog_category::view
  methods: GET

paloma_catalog_category_product:
  path: /c/todo/p/todo
  controller: paloma_shop.controller.catalog_product::viewInCategory
  methods: GET

paloma_catalog_product:
  path: /p/todo
  controller: paloma_shop.controller.catalog_product::view
  methods: GET
