paloma_catalog_home:
  path: /
  controller: paloma_shop.controller.catalog_home::view
  methods: GET

paloma_catalog_search:
  path: /search
  controller: paloma_shop.controller.catalog_search::view
  methods: [ GET, POST ]

paloma_catalog_category_product:
  path: /{categorySlug}:{categoryCode}/{productSlug}:{itemNumber}
  requirements:
    categorySlug: '.*'
    categoryCode: '[^:/]+'
    productSlug: '.*'
    itemNumber: '[^:]+'
  controller: paloma_shop.controller.catalog_product::viewInCategory
  methods: GET

paloma_catalog_category:
  path: /{categorySlug}:{categoryCode}
  requirements:
    categorySlug: '.*'
    categoryCode: '[^:]+'
  controller: paloma_shop.controller.catalog_category::view
  methods: GET

paloma_catalog_product:
  path: /p/{productSlug}:{itemNumber}
  requirements:
    productSlug: '.*'
    itemNumber: '[^:]+'
  controller: paloma_shop.controller.catalog_product::view
  methods: GET