paloma_checkout_start:
  path: /
  controller: paloma_shop.controller.checkout::start
  methods: GET

paloma_checkout_success:
  path: /success
  controller: paloma_shop.controller.checkout::success
  methods: GET

paloma_checkout_payment_start:
  path: /payment/start
  controller: paloma_shop.controller.payment::start
  methods: GET

paloma_checkout_payment_success:
  path: /payment/success
  controller: paloma_shop.controller.payment::success
  methods: [ GET, POST ]

paloma_checkout_payment_complete:
  path: /payment/complete
  controller: paloma_shop.controller.payment::complete
  methods: GET

paloma_checkout_payment_cancel:
  path: /payment/cancel
  controller: paloma_shop.controller.payment::cancel
  methods: [ GET, POST ]

paloma_checkout_payment_error:
  path: /payment/error
  controller: paloma_shop.controller.payment::error
  methods: [ GET ]

# Separate POST route to prevent loss of session
paloma_checkout_payment_error_post:
  path: /payment/error
  controller: paloma_shop.controller.payment::errorPost
  methods: [ POST ]

paloma_checkout_state:
  path: /{state}
  controller: paloma_shop.controller.checkout::state
  methods: GET
  requirements:
    state: '.*'
