paloma_security_login:
  path: /login
  controller: paloma_shop.controller.security::login
  methods: [ POST, GET ]

paloma_security_logout:
  path: /logout
  methods: [ POST, GET ]

paloma_security_password_reset_confirm:
  path: /password-reset/confirm
  controller: paloma_shop.controller.security::confirmPasswordReset
  methods: GET